title: Ciberseguridad germa15
email: german.benver@outlook.com
description: >-
  Blog de cibersegurdad basado en conocimientos y experiencias propias,
  de un fanático de la seguridad informática para el que quiera leer.
baseurl: "/Ciber" # la subcarpeta de tu sitio en GitHub Pages
url: "https://germa15.github.io" # el dominio base de tu GitHub Pages
twitter_username: kzu1500
github_username: germa15

# Build settings
theme: jekyll-theme-chirpy
# remote_theme: cotes2020/jekyll-theme-chirpy # Si la anterior sigue dando error de 404 de descarga, prueba esta.

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
