name: Deploy Jekyll Chirpy Blog to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate que esta sea tu rama principal (es la que usas)
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job para construir el sitio Jekyll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Si tu tema tiene submódulos (Chirpy los usa para algunos assets),
          # inicializa los submódulos de forma recursiva.
          submodules: true
          # fetch-depth: 0 # Opcional: Puede ser necesario si tienes un historial muy largo
                            # o si los submódulos tienen problemas. Si el workflow falla aquí, descomenta.

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Versión de Ruby compatible con Jekyll 4.x y Chirpy 7.x
          bundler-cache: true # Caching de las gemas para builds más rápidos (instala desde Gemfile.lock o Gemfile)

      - name: Install Dependencies # <--- ¡ESTE PASO FALTABA O NO ESTABA BIEN!
        # Instala las gemas especificadas en tu Gemfile, incluyendo Jekyll y el tema Chirpy.
        # `bundler-cache: true` en el paso anterior optimiza esto.
        run: bundle install

      - name: Build Jekyll Site
        # JEKYLL_ENV=production optimiza la salida.
        # Tu _config.yml usa 'theme: jekyll-theme-chirpy', que se instalará como gema.
        run: JEKYLL_ENV=production bundle exec jekyll build --verbose

      - name: Upload artifact for GitHub Pages
        # Sube la carpeta _site generada por Jekyll para el despliegue.
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site # Directorio donde Jekyll construye el sitio

  # Job para desplegar el sitio en GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Este job depende del job 'build' para asegurar que el sitio se construya primero

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
