name: Deploy Jekyll Chirpy Blog to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate que esta sea tu rama principal (es la que usas)
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job para construir el sitio Jekyll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          # fetch-depth: 0 # Opcional: Puede ser necesario si tienes un historial muy largo
                            # o si los submódulos tienen problemas. Si el workflow falla aquí, descomenta.

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          # ¡IMPORTANTE! bundler-cache: true se desactiva aquí para que 'bundle install --path vendor/bundle' funcione sin conflicto.
          # bundler-cache: true

      # Eliminamos el paso 'Install Bundler' si lo tenías separado

      - name: Install Dependencies to Vendor Bundle # <--- ¡NUEVO PASO DE INSTALACIÓN CLAVE!
        # Instala todas las gemas (incluyendo Jekyll y Chirpy) en la carpeta local 'vendor/bundle'.
        # Esto nos da control directo sobre su ubicación.
        run: bundle install --path vendor/bundle

      # Eliminamos el paso 'Add Bundler to PATH' que habíamos probado antes.

      - name: Build Jekyll Site # <--- ¡PASO DE CONSTRUCCIÓN CORREGIDO!
        # Primero, añade el directorio de binarios de 'vendor/bundle' a la PATH.
        # Luego, ejecuta Jekyll directamente desde esa PATH.
        run: |
          export PATH=$(pwd)/vendor/bundle/bin:$PATH
          JEKYLL_ENV=production jekyll build --verbose
        shell: bash # Asegura que se usa Bash para el comando 'export PATH'

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Job para desplegar el sitio en GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Este job depende del job 'build' para asegurar que el sitio se construya primero

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
